#!/bin/bash
mkdir VariantLists

grep '^everycomp:q/.*_carpet$' $1 > VariantLists/EverycompCarpets.txt
grep '^everycomp:q/.*_hedge$' $1 > VariantLists/EverycompHedges.txt
grep '^everycomp:q/.*hollow_.*_log' $1 > VariantLists/EverycompQuarkHollowLogs.txt
grep '^everycomp:q/.*/.*_post' $1 > VariantLists/EverycompPosts.txt
grep '^everycomp:tc/.*/.*_boardwalk' $1 > VariantLists/EverycompBoardwalks.txt
grep '^everycomp:tf/.*/.*_banister' $1 > VariantLists/EverycompBanisters.txt
grep '^everycomp:abd/.*/fence_log_.*' $1 > VariantLists/EverycompLogFences.txt
grep '^everycomp:abd/.*/wall_.*_log' $1 > VariantLists/EverycompLogWallsPre.txt
grep 'everycomp:abd/deep_aether/' VariantLists/EverycompLogWallsPre.txt | grep -v 'stripped' | cat - VariantLists/EverycompLogWallsPre.txt | sort | uniq --unique > VariantLists/EverycompLogWalls.txt
grep '^everycomp:abd/.*/wall_.*planks' $1 > VariantLists/EverycompPlankWalls.txt
grep '^everycomp:db/.*/.*_beam$' $1 > VariantLists/EverycompBeams.txt
grep '^everycomp:db/.*/.*_support$' $1 > VariantLists/EverycompSupports.txt
grep '^everycomp:db/.*/.*_palisade$' $1 > VariantLists/EverycompPalisades.txt
