modules_right = []

[general]
	disable_mod = false
	hide_bossbar = true
	shadow_text = true
	auto_start = false
	animationSpeed = 1.3
	hide_debug_crosshair = false
	background_color = 5263440
	space_modules = false
	always_show_profiler = false
	animations = true
	fontScale = 1.0
	hide_sidebar = true
	always_show_tps = false

[[modules_left]]
	name = "minecraft"
	name_color = 10506797
	value_color = 43520
	enabled = true

	[modules_left.lines]
		minecraft = true

[[modules_left]]
	color_high = 5635925
	color_med = 16777045
	name = "fps"
	enabled = true
	color_low = 16733525

	[modules_left.lines]
		fps = true

[[modules_left]]
	empty_lines = 1
	name = "empty"
	enabled = true

	[modules_left.lines]
		nothing = true

[[modules_left]]
	memory_color_toggle = true
	time_format = "HH:mm:ss"
	name = "system"
	name_color = 43520
	value_color = 5636095
	enabled = true

	[modules_left.lines]
		opengl_version = false
		allocation_rate = true
		display = false
		java_version = false
		gpu_driver = false
		memory_usage = true
		allocated_memory = true
		cpu = false
		gpu_utilization = true
		time = false
		gpu = false

[[modules_left]]
	empty_lines = 1
	name = "empty"
	enabled = true

	[modules_left.lines]
		nothing = true

[[modules_left]]
	name = "location"
	name_color = 43520
	value_color = 5636095
	enabled = true

	[modules_left.lines]
		light = true
		biome = true
		rotation = true
		facing = true
		slime_chunk = true
		local_difficulty = true
		day_ticks = true
		days_played = true
		dimension = true
		highest_block = true
		highest_block_server = true
		light_server = true

