
[gui]
	#The option below changes the behavior of the capture input feature:
	#PER_BLOCK - The capture input value is saved between UI opens on a per computer/monitor/robot basis
	#SHARED_BETWEEN_TYPE - The capture input value is saved between UI opens and is shared between all
	#blocks of the same type, e.g. enabling the setting on one monitor will enable it for all monitors but not for a computer
	#GLOBAL_CAPTURE - The capture input value is saved between UI opens and is shared between all devices that have the option
	#Allowed Values: PER_BLOCK, SHARED_BETWEEN_TYPE, GLOBAL_CAPTURE
	captureInputMode = "PER_BLOCK"
	#Defines whether input capture should be enabled by default in a session
	captureInputDefaultState = false

